fix: Uniform audience parsing
ory/fosite pull request #505
Opened 2020-10-03 07:31 UTC by mitar

## Proposed changes

Making sure audience parsing in authorize flow is the same as in access flow. Consistency.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
- [x] I have read the [security policy](../security/policy)
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation within the code base (if appropriate)

2020-10-06 10:44 UTC, aeneasr requested changes
Could you add a regression test for this please?

2020-10-07 03:39 UTC, mitar commented
Added test.

2020-10-11 18:50 UTC, aeneasr approved these changes

2020-10-11 18:50 UTC, aeneasr commented
Thank you for the great contributions this week, @mitar!

2020-10-11 18:51 UTC, merged

2020-10-13 17:16 UTC, mitar commented
BTW, could you make a release sometime soon? So that I can update stuff on our side.

2020-10-20 10:34 UTC, aeneasr commented
Sorry about the delay - it's done! By the way, you can reference git hashes and branches in `go.mod` so need to wait to wait for releases :)

2020-10-20 15:51 UTC, mitar commented
I know, but it is cleaner to have versions. :-)