Fix sha alg name in error message and go doc
ory/fosite pull request #571
Opened 2021-03-28 01:04 UTC by vineet-garg

## Related issue

N/A

## Proposed changes

Update the messages and document with new algorithm name. The algorithm was changed earlier and it seems the references were not updated.
## Checklist

- [ x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ x] I have read the [security policy](../security/policy).
- [x ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

2021-03-28 01:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ory/fosite?pullRequest=571) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ory/fosite?pullRequest=571) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ory/fosite?pullRequest=571) it.</sub>

2021-03-29 08:27 UTC, aeneasr requested changes
Awesome, thank you for your contribution! This looks pretty good and I have some ideas how to improve it further :)

2021-03-29 08:27 UTC, aeneasr commented on token/hmac/hmacsha.go
> +// Package hmac is the default implementation for generating and validating challenges. It uses HMAC-SHA512_256 to
The correct naming is `SHA-512/256`

```suggestion
// Package hmac is the default implementation for generating and validating challenges. It uses SHA-512/256 to
```

There are also a couple more places in this document that can be updated :)

2021-03-29 09:28 UTC, aeneasr approved these changes
Awesome, thank you! 🎉 Your contribution makes Ory better :)

2021-03-29 09:28 UTC, merged

2021-03-29 09:34 UTC, vineet-garg commented
> Awesome, thank you! 🎉 Your contribution makes Ory better :)

Thank you!

2021-03-29 09:36 UTC, aeneasr commented
Looks like I overlooked the test failure, could you please fix the test?

https://app.circleci.com/pipelines/github/ory/fosite/352/workflows/0432cd13-c765-46d7-85dd-e7daea1748d1/jobs/1111

Thank you!

2021-03-29 10:07 UTC, vineet-garg commented
> Looks like I overlooked the test failure, could you please fix the test?
> 
> https://app.circleci.com/pipelines/github/ory/fosite/352/workflows/0432cd13-c765-46d7-85dd-e7daea1748d1/jobs/1111
> 
> Thank you!

absolutely, I have a new PR, I will include in that now.