Feat/device authorization grant
ory/fosite pull request #691
Opened 2022-07-29 14:13 UTC by pedrule

## Related Issue or Design Document

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got green light (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation within the code base (if appropriate).

## Further comments

2022-07-29 14:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ory/fosite?pullRequest=691) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ory/fosite?pullRequest=691) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ory/fosite?pullRequest=691) it.</sub>

2022-08-08 05:59 UTC, james-d-elliott requested changes
Think my review addresses one of the issues, not sure about the rest here: https://app.circleci.com/pipelines/github/ory/fosite/717/workflows/ad2e8279-e2a8-4e6b-8452-68d1556330a4/jobs/2287

2022-08-08 05:59 UTC, james-d-elliott commented on device_authorize_request_handler.go
> + func (f *Fosite) NewDeviceAuthorizeRequest(ctx context.Context, r *http.Request) (DeviceAuthorizeResponder, error) {
```suggestion
 func (f *Fosite) NewDeviceAuthorizeRequest(ctx context.Context, r *http.Request) (DeviceAuthorizeRequester, error) {
```

2022-08-08 05:59 UTC, james-d-elliott commented on device_authorize_request_handler.go
> + func (f *Fosite) NewDeviceAuthorizeRequest(ctx context.Context, r *http.Request) (DeviceAuthorizeResponder, error) {
I think this is the appropriate change as per the test suite.

2022-08-25 11:50 UTC, closed without merging

2022-08-25 11:50 UTC, pedrule commented
No more needed, a new one is coming