feat: Move OTEL to a new 'InstrumentedFosite'
ory/fosite pull request #763
Opened 2023-08-05 03:34 UTC by vivshankar

The recent change in [#761 ] introduces OTEL as part of Fosite. While this is valuable, this should
be provided as a wrapper and not as a hard wired part of Fosite, which is meant to be a SDK. Also,
popular instrumentation options and APM vendors have some level of support for OTEL but shine
when their wrapper SDKs are used that do not always comply with OTEL interfaces. See New Relic
and Instana SDKs for reference.

This change proposes that OTEL should be an opt-in as part of a wrapper implementation of Fosite
that is called `InstrumentedFosite` under the `otel` package. It also offers a pattern that can be applied
to any code blocks and handlers that should be instrumented to derive maximum benefits from a telemetry
perspective. For example - there may be no value in instrumenting a code block that interfaces with no
external components beyond the overall telemetry offered at a HTTP middleware level, whereas there
may be a great deal of value instrumenting call outs to external APIs and databases.

## Related Issue or Design Document

#761 

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [x] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added the necessary documentation within the code base (if appropriate).

## Further comments

2023-08-05 04:23 UTC, james-d-elliott commented
Tests seem to just be failing due ory/hydra using a PR in go.mod. I like this change, I did some experimentation with it in making github.com/ory/fosite/otel it's own module so it's entirely standalone however I could not get it working, maybe it's unnecessary due to pruning and github.com/ory/x contains the imports anyway.

2023-08-07 09:16 UTC, aeneasr requested changes
Thank you for the PR! I think it's nice to abstract away tracing and at the same time am critical of this approach. We will most likely add more OTEL tracing to lower-level functions and then this approach will no longer work (as well) without significant code wiring.

I think otel is a solid standard and would recommend to just go with it for now. If you want wrapping - you still can do that in your own codebase consuming Fosite!

2023-08-07 10:39 UTC, vivshankar commented
The way we abstracted this for future proofing is to introduce a metrics interface that allows you to swap in providers as needed. OTEL is great but is not completely adopted by major vendors (referenced in my post). Also the current implementation takes away any flexibility for adopters to use different libraries.

I am happy to take another stab at this to put it in Fosite directly if that will be acceptable

2023-08-07 11:53 UTC, vivshankar commented
@aeneasr Just got to my machine. To substantiate further, we could minimally add a config parameter to control the instrumentation. I was also thinking for handlers to add a wrapper handler that basically does the same thing and it becomes a simple matter of adding that to your compose factory/handler list.

For custom code blocks, it is simple enough to add an interface for spans and transactions.

2023-08-07 11:56 UTC, aeneasr commented
I don't think that we want to maintain an abstraction for telemetry in Fosite, especially as we are quite happy with otel at the moment.

If you don't have an otel compatible system, you can set the otel tracer to noop/nil in which case nothing happens. And you can still wrap Fosite any way you want to add instrumentation.

Being honest, I don't the value of doing a lot of work here right now.

2023-08-07 12:03 UTC, closed without merging