Remove redundant map access
ory/fosite pull request #775
Opened 2023-11-10 07:10 UTC by dtam-cybozu

Remove a redundant check for whether an element is present in a map. Since we return the zero value of a `time.Time` anyway, it's simpler to use the single return value version to access the map.
## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

2023-11-10 13:14 UTC, aeneasr requested changes
I believe that this will panic if the key does not exist

2023-11-10 14:27 UTC, dtam-cybozu commented
> I believe that this will panic if the key does not exist

I don't think this is right. See https://go.dev/ref/spec#Index_expressions

> For a of [map type](https://go.dev/ref/spec#Map_types) M:
>
> - x's type must be [assignable](https://go.dev/ref/spec#Assignability) to the key type of M
> - if the map contains an entry with key x, a[x] is the map element with key x and the type of a[x] is the element type of M
> - if the map is nil or does not contain such an entry, a[x] is the [zero value](https://go.dev/ref/spec#The_zero_value) for the element type of M

Here is a Go Playground example https://go.dev/play/p/udUlbIUWIfq

2023-11-10 22:16 UTC, james-d-elliott commented
Yeah this will not panic and will return exactly the same output. I would imagine there is a test in this scenario or one could be easily added to prove unchanged function.

2023-11-13 02:09 UTC, dtam-cybozu commented
BTW @aeneasr if the session itself is nil then a call to `GetExpiresAt` *will* panic but this is a separate discussion.

Anyway, I've added a test to show this does not panic.

2023-11-13 12:50 UTC, aeneasr approved these changes

2023-11-13 12:51 UTC, aeneasr commented
Thank you for the follow up - I think I was confused because it would panic if we had a pointer and would try to access it. Since we don't have either, this is fine! :)

2023-11-13 12:51 UTC, merged